[tool.poetry]
name = "poli-capstone-project"
version = "0.1.0"
description = ""
authors = ["Gabriel Benvegmi"]
readme = "README.md"
packages = [{include = "poli_capstone_project"}]

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
